name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Gradle
        run: |
          sudo apt update
          sudo apt install -y gradle

      # Create missing wrapper automatically
      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AppKiller-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
